version: '3'
services:
  api:
    build:
      context: ../
      dockerfile: docker/api/Dockerfile
    image: ${PROJECT_NAME}-api
    restart: unless-stopped
    container_name: ${PROJECT_NAME}-api
    ports:
      - '${PORT}:${PORT}'
    networks:
      - my-network
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
      - ${HOME}/.aws/credentials:/root/.aws/credentials
      - ${HOME}/.aws/config:/root/.aws/config
