version: '3'
services:
  api:
    build:
      target: localbuilder
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials
      - ${HOME}/.aws/config:/root/.aws/config
  localstack:
    image: localstack/localstack
    container_name: ${PROJECT_NAME}-localstack
    restart: unless-stopped
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      - my-network
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
