version: '3'
services:
  api:
    build:
      context: ../
      dockerfile: docker/api/Dockerfile
    image: ${PROJECT_NAME}-api
    restart: unless-stopped
    container_name: ${PROJECT_NAME}-api
    ports:
      - '${PRE_PORT}4000:4000'
    networks:
      - my-network
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
