version: '3'
services:
  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-database
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:3306'
    networks:
      - my-network
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    depends_on:
      - db
    ports:
      - '${DB_TOOL_PORT}:80'
    networks:
      - my-network
    restart: unless-stopped
volumes:
  my-db:
    name: ${PROJECT_NAME}-db
